# Generated by Django 4.2 on 2024-05-17 01:05

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijk', length=10, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('partNumber', models.CharField(max_length=20)),
                ('quntity', models.PositiveSmallIntegerField(max_length=5)),
                ('category', models.CharField(max_length=20)),
                ('barcode', models.PositiveSmallIntegerField(max_length=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='orders_image/')),
                ('dedicatedSupplier_status', models.BooleanField(default=False)),
                ('publicSupplier_status', models.BooleanField(default=False)),
                ('relatedGroup_status', models.BooleanField(default=False)),
                ('guarantee_status', models.BooleanField(default=False)),
            ],
        ),
    ]
