# Generated by Django 4.2 on 2024-05-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='barcode',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='quntity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
