# Generated by Django 4.2 on 2024-05-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_barcode_alter_order_quntity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pid',
        ),
        migrations.AlterField(
            model_name='order',
            name='barcode',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orders_image/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='partNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
