# Generated by Django 4.2 on 2024-05-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_pid_alter_order_barcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quntity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dedicatedSupplier_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='partNumber',
        ),
        migrations.RemoveField(
            model_name='order',
            name='publicSupplier_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='relatedGroup_status',
        ),
        migrations.AddField(
            model_name='order',
            name='dedicated_supplier_status',
            field=models.BooleanField(default=False, verbose_name='Dedicated Supplier Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='part_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Part Number'),
        ),
        migrations.AddField(
            model_name='order',
            name='public_supplier_status',
            field=models.BooleanField(default=False, verbose_name='Public Supplier Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='related_group_status',
            field=models.BooleanField(default=False, verbose_name='Related Group Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='guarantee_status',
            field=models.BooleanField(default=False, verbose_name='Guarantee Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orders_image/', verbose_name='Image'),
        ),
    ]
