# Generated by Django 4.2 on 2024-05-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('phone_Number', models.CharField(max_length=15)),
                ('work_field', models.CharField(max_length=50)),
            ],
        ),
    ]
